### ISSUE TITLE
ExecutableNotFound: failed to execute ['dot', '-Tsvg']

### ISSUE THREAD

**Issue by Jacques2101** [xflr6/graphviz#123]
I had installed Graphviz with on MacOS: 
```
conda install -c conda-forge python-graphviz
```
I get this error message with my code below :  

**The bug description**
got an error message with the code below 
`ExecutableNotFound: failed to execute ['dot', '-Tsvg'], make sure the Graphviz executables are on your systems' PATH`

**My code**
```
import arviz as az
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import pymc3 as pm
import scipy.stats as stats
import seaborn as sns

with pm.Model() as model:
    mu = pm.Normal("mu", mu=0, sigma=1)
    obs = pm.Normal("obs", mu=mu, sigma=1, observed=np.random.randn(100))

    idata = pm.sample(2000, tune=2000, return_inferencedata=True)

pm.model_to_graphviz(model)
```

I searched answer on internet and then added to my code but without help: 
```
import os
os.environ["PATH"] += os.pathsep + "/Users/jacques/opt/anaconda3/envs/bayes/lib/graphviz"
import arviz as az
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import pymc3 as pm
import scipy.stats as stats
import seaborn as sns

with pm.Model() as model:
    mu = pm.Normal("mu", mu=0, sigma=1)
    obs = pm.Normal("obs", mu=mu, sigma=1, observed=np.random.randn(100))

    idata = pm.sample(2000, tune=2000, return_inferencedata=True)

pm.model_to_graphviz(model)
```

**Additional context**
- PyMC3 Version: 3.10
- Theano Version: 1.0.4
- Python Version: 3.8.2
- Graphviz: 2.40.1 
- Operating system: macOS Big Sur 1.1

**Comment by xflr6** [comment]
Thanks for the detailed report.

You seem to be using the (downstream) conda-forge [python-graphviz](https://anaconda.org/conda-forge/python-graphviz) package: [python-graphviz-feedstock](https://github.com/conda-forge/python-graphviz-feedstock).

Can you check if you get the same error installing the vanilla version of [Graphviz](https://www.graphviz.org/download/) and pip-installing the [vanilla version of this package](https://graphviz.readthedocs.io/en/stable/manual.html#installation)?

**Comment by Jacques2101** [comment]
`dot -V` gave me: `dot - graphviz version 2.40.1 (20161225.0304)`
Finally, this works: 
```
import os
os.environ["PATH"] += os.pathsep + "/Users/jacques/opt/anaconda3/envs/bayes/bin"
```

But it seems strange from my point of view that I need to do that. 

Did I install the wrong version as you seem to suggest ? What should I do ? Remove the old one and install with `pip install graphviz`

Thx for your return.

**Comment by xflr6** [comment]
Thanks.

> `os.environ["PATH"] += os.pathsep + "/Users/jacques/opt/anaconda3/envs/bayes/bin"`
> But it seems strange from my point of view that I need to do that.

+1, this should not be needed: If you don't use `conda`, it should be enough to install Graphviz on your system and pip-install `graphviz` either into your system Python or a `venv` that you are using.

If the method you are using to install Graphviz does not put the executeables on your system's PATH, you might need to ensure that *once* to finalize the installation (how depends on platform and method).

If you still need to do hard-coded PATH adaptations from Python code (shold not be needed with a working Graphviz installation), you might still be pointing to the [`conda-forge` distribution of  Graphviz](https://anaconda.org/conda-forge/graphviz) instead of the vanilla one (`anaconda3` in the path), so it might be worth removing that to verify that the issue is not in this library.

If the issue is specific to the `conda-forge` distribution, please report downstream:
https://github.com/conda-forge/python-graphviz-feedstock

**Comment by Jacques2101** [comment]
I just delete all my environment and reinstall it. 
To be clear to install Graphviz I should only do: 
`pip install graphviz`
with that I won't need to add the path ???
thx

**Comment by xflr6** [comment]
Let me try to clarify  (also see the [documentation](https://graphviz.readthedocs.io/en/stable/manual.html#installation)):
- to install the vanilla version of this package (rather than the [conda one](https://anaconda.org/conda-forge/python-graphviz)) use `pip install graphviz`
- to be able to use this package, it requires a working installation of [Graphviz](https://www.graphviz.org/download/) (working `dot -V`)

There is also a separate/independent `conda-forge` distributions of this package ([anaconda page](https://anaconda.org/conda-forge/python-graphviz)) that internally depends on the `conda-forge` adaptation of Graphviz ([anaconda page](https://anaconda.org/conda-forge/graphviz)) (and automatically installs the latter if you install the former AFAIU):
- if the issue is specific to either of them, please report upstream:
- https://github.com/conda-forge/python-graphviz-feedstock
- https://github.com/conda-forge/graphviz-feedstock

Unfortunately, the Anaconda pages don't seem to provide links to their package source/maintainers.

**Comment by Jacques2101** [comment]
Sorry but the second part is not clear: to be able to use this package, it requires a working installation of Graphviz (working dot -V)what should I do here ? thxs.  Cordialement   De : Sebastian Bank <notifications@github.com>Date : dimanche, 3 janvier 2021 à 20:44À : xflr6/graphviz <graphviz@noreply.github.com>Cc : Jacques <jacques.tebeka@gmail.com>, Author <author@noreply.github.com>Objet : Re: [xflr6/graphviz] ExecutableNotFound: failed to execute ['dot', '-Tsvg'] (#123)Let me try to clarify (also see the documentation):to install the vanilla version of this package (rather than the conda one) use pip install graphvizto be able to use this package, it requires a working installation of Graphviz (working dot -V)There is also a separate/independent conda-forge distributions of this package (anaconda page) that internally depends on the conda-forge adaptation of Graphviz (anaconda page) (and automatically installs the latter if you install the former AFAIU):if the issue is specific to either of them, please report upstream:https://github.com/conda-forge/python-graphviz-feedstockhttps://github.com/conda-forge/graphviz-feedstockUnfortunately, the Anaconda pages don't seem to provide links to their package source/maintainers.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by xflr6** [comment]
> Sorry but the second part is not clear:
>>  to be able to use this package, it requires a working installation of [Graphviz](https://www.graphviz.org/download/) (working `dot -V`)

> what should I do here ?

Follow the [Graphviz installation instructions](https://www.graphviz.org/download/) for your platform (as I don't have experience with MacOS, I don't know about the details, but I think that the installation should give you a working `dot` on the command line).
