### ISSUE TITLE
Add conda package name to README and doc

### ISSUE THREAD

**Issue by phil-blain** [xflr6/graphviz#129]
Hi, 

I think it could be nice to mention the name of the conda-forge package for this project (`python-graphviz`) in the REAMDE and in the doc. There are "graphviz", "pygraphviz", "python-graphviz" so it's a little confusing for newbies. :)

Cheers!

**Comment by xflr6** [comment]
Thanks. Sounds good.

That would be [conda-forge/python-graphviz-feedstock](https://github.com/conda-forge/python-graphviz-feedstock), right (https://anaconda.org/conda-forge/python-graphviz)?

There is also [ContinuumIO/anaconda-recipe/.../python-graphviz](https://github.com/ContinuumIO/anaconda-recipes/tree/master/python-graphviz) (https://anaconda.org/anaconda/python-graphviz), but the `conda-forge` package above seems to be more popular.

The downstream `conda-forge` distribution used to include a patch that was needed to make it work with corresponding distribution of Graphviz, and issues with that they sometimes where reported here (although it's not maintained by me), which is why I was a bit cautious to link to that. However, that was recently removed, so it should be fine to link this (and possibly other) downstream distributions in the installation documentation.

**Comment by xflr6** [comment]
Fixed in ac316a2fffb26fce7005ed6de60f738042403047
