### ISSUE TITLE
Add support for neato engine no-op command-line flag

### ISSUE THREAD

**Issue by clayms** [xflr6/graphviz#131]
Is it possible to use the neato engine no-op command-line flag (`-n` CLI flag) to add to an existing graph without altering the current node locations?

See "-n[num]" in https://graphviz.gitlab.io/doc/info/command.html

[Neato Layout Manual](https://graphviz.gitlab.io/pdf/dot.1.pdf).

**Comment by xflr6** [comment]
Thanks. Marking this as enhancement.

Would you like to give it a try?

Probably similar to the `formatter` argument: https://github.com/xflr6/graphviz/blob/a542d0482ca20009424741bc1fd1a28354434b8f/graphviz/files.py#L202-L205

https://github.com/xflr6/graphviz/blob/a542d0482ca20009424741bc1fd1a28354434b8f/graphviz/files.py#L143-L144

**Comment by xflr6** [comment]
See https://graphviz.gitlab.io/doc/info/command.html#-n

**Comment by neogeno** [comment]
+1 - can someone give me some advice to add a PR myself so that I can pass -n2 to the neato engine?

**Comment by xflr6** [comment]
The code moved around a bit since then (better structure).

We need a new argument similar to the `formatter` argument:

https://github.com/xflr6/graphviz/blob/ee3ae102eb2c144ec36f0ca801ea590b85143ba4/graphviz/backend/dot_command.py#L15-L19

https://github.com/xflr6/graphviz/blob/ee3ae102eb2c144ec36f0ca801ea590b85143ba4/graphviz/backend/rendering.py#L197-L206

Also the `overload` annoations above.

https://github.com/xflr6/graphviz/blob/ee3ae102eb2c144ec36f0ca801ea590b85143ba4/graphviz/backend/piping.py#L15-L19

Also the other `pipe` functions above.

https://github.com/xflr6/graphviz/blob/ee3ae102eb2c144ec36f0ca801ea590b85143ba4/graphviz/rendering.py#L22-L36

https://github.com/xflr6/graphviz/blob/ee3ae102eb2c144ec36f0ca801ea590b85143ba4/graphviz/piping.py#L52-L59

Also `overload` and the private implementations above.

Not sure about the naming, maybe `neato_no_op`, or `neato_no_op_num` (type: `Union[bool, int]`, maybe `Optional`)?

Needs test coverage naturally.

**Comment by xflr6** [comment]
Work in progress in 4ac5a2516838413b7c5d37af96285bb8fa4011bf.

**Comment by xflr6** [comment]
Added in [version `0.20`](https://pypi.org/project/graphviz/0.20/#files), closing.
