### ISSUE TITLE
Iterate through nodes and edges?

### ISSUE THREAD

**Issue by jackmaney** [xflr6/graphviz#19]
I've looked through the documentation, and I've also glanced at the source code, so my apologies if I've missed this feature, but could we get methods that allow us to iterate through the nodes and/or edges that have been added to an existing `Dot` object?

Off the top of my head, one way to implement this would to have attributes of `_node_list` and `_edge_list` that are initialized at `[]`. They're then updated when adding nodes and edges, and we can tack on a `nodes` method to return `_node_list` and allow calling the `edges` method with no (user-supplied) arguments to get a simple iterator of edge data, eg:

```
def node(self, name, label=None, _attributes=None, **attrs):
        """Create a node.
        Args:
            name: Unique identifier for the node inside the source.
            label: Caption to be displayed (defaults to the node name).
            attrs: Any additional node attributes (must be strings).
        """
        name = self.quote(name)
        attributes = self.attributes(label, attrs, _attributes)
        self.body.append(self._node % (name, attributes))
        node_dict = {"name": name, "label": label}
        self._nodes.append({"name": name, "label": label, "attributes": attrs})

def nodes(self):
    """Provides a list of node data (in the form of dicts) for nodes that have been added."""
    return self._nodes

def edge(self, tail_name, head_name, label=None, _attributes=None, **attrs):
        """Create an edge between two nodes.
        Args:
            tail_name: Start node identifier.
            head_name: End node identifier.
            label: Caption to be displayed near the edge.
            attrs: Any additional edge attributes (must be strings).
        """
        tail_name = self.quote_edge(tail_name)
        head_name = self.quote_edge(head_name)
        attributes = self.attributes(label, attrs, _attributes)
        edge = self._edge % (tail_name, head_name, attributes)
        self.body.append(edge)
        self._edges.append({"tail": tail_name, "head": head_name, "attributes": attrs})

def edges(self, tail_head_iter=None):
        """Create a bunch of edges or iterate through existing edges.
        Args:
            tail_head_iter: Iterable of (tail_name, head_name) pairs or None.
                If not provided, then a list of edge data is returned.
        """
        if tail_head_iter is not None:
            edge = self._edge_plain
            quote = self.quote_edge
            tail_head_iter = [(quote(t), quote(h)) for t, h in tail_head_iter]
            self.body.extend(edge % (t, h)
                for t, h in tail_head_iter)
            self._edges.extend([{"tail": t, "head": h} for t, h in tail_head_iter])
        else:
            return self._edges
```

This is probably a bit incorrect, as `_attributes` and `attrs` probably need to be merged. Now that I think about it, I'm not sure why there are two arguments that seem to provide the same thing (`_attributes` is supposed to be an object, right?). Also, we could be fancier and have separate `Node` and `Edge` objects to hold this data instead of `dict`s, but I'm not sure that's terribly necessary.

I'd be willing to make a pull request if this feature would be welcome.

**Comment by xflr6** [comment]
Well, it is a deliberate decision *not* to remember all graph-building method-call arguments: The library is exactly for creating (rendering, etc.) the DOT code lines for a graph, not as a generic library for representing graphs (like e.g. NetworkX). Thereby, `Graph` and `Digraph` can be kept relatively simple (basically append-only lists of strings with DOT code). Typically, users have the collection of nodes and edges they want to render somewhere inside *their* objects/data structures (why duplicate here?).

Wouldn't it be cleaner to put the node/edge-gathering functionality you want to implement into its own class (that might use `graphviz` under the hood) rather than changing the interface here (composition over inheritance)?

AFAIR `pygraphviz` and `pydot` provide fully editable graph objects (which makes more sense for them, as they can also *parse* DOT code), see e.g. [nodes_iter](https://pygraphviz.github.io/documentation/pygraphviz-1.3rc1/reference/agraph.html#pygraphviz.AGraph.nodes_iter).
