### ISSUE TITLE
Graphviz on ipad pro not supported

### ISSUE THREAD

**Issue by ghltshubh** [xflr6/graphviz#226]
I am using Juno app to run jupyter notebook on my ipad however I am facing 
`OSError: Subprocesses are not supported on the current platform` while using the graphviz library

**Comment by xflr6** [comment]
Thanks for flagging.

Unfortunately it seems to be by design that iOS does not provide a way create subprocesses as part of its sandboxing/hardening philosophy, so this applies to any app including Python ones, see https://peps.python.org/pep-0730/#posix-compliance for details on the Python side.

From https://docs.python.org/3/library/subprocess.html

>[Availability](https://docs.python.org/3/library/intro.html#availability): not Android, not iOS, not WASI.

One thing one might try as an alternative would be see if you can get https://pygraphviz.github.io (from https://github.com/xflr6/graphviz?tab=readme-ov-file#see-also) installed and working on iOS in some way, since AFAIU that library does the rendering via a C-interface that IIUC does not create a separate process (unlike this library whose rendering implementation is basically `subprocess.run(['dot', ...)`).
