### ISSUE TITLE
downloading graphviz automatically?

### ISSUE THREAD

**Issue by xoviat** [xflr6/graphviz#39]
pypandoc has a method to download pandoc automatically. graphviz should do the same.

**Comment by xflr6** [comment]
how about `pip download` ([docs](https://pip.pypa.io/en/stable/reference/pip_download/))? even implements caching:
```bash
$ pip download graphviz
Collecting graphviz
  Using cached graphviz-0.7-py2.py3-none-any.whl
  Saved c:\users\user\desktop\graphviz-0.7-py2.py3-none-any.whl
Successfully downloaded graphviz
```

**Comment by xoviat** [comment]
that's not what I'm talking about. I'm talking about download the executable that this library requires automatically

**Comment by xflr6** [comment]
Ah, okay, thanks. This may be out of scope for this module as it is difficult to do for all supported platforms at once (or to test). If you want binaries matched with a Python environment, [anaconda](https://www.continuum.io/downloads) might be something to consider (includes both graphviz Python libraries as well as Graphviz binaries).

**Comment by xoviat** [comment]
Actually most of the work has already been done [here](https://github.com/bebraw/pypandoc/blob/master/pypandoc/pandoc_download.py).

It's a simple matter of parsing links [here](http://www.graphviz.org/Download_macos.php), [here](http://www.graphviz.org/Download_windows.php), and [here](http://www.graphviz.org/Download_linux_ubuntu.php) and then modifying the script a bit so that everything falls nicely into place.

**Comment by johnyf** [comment]
GraphViz is distributed separately, and is available in package managers for the most widely used operating systems. As far as I can tell, it is used as an external program by the Python package `graphviz`, so no need to compile any bindings. Therefore no need to install it as part of the `graphviz` package.

[PEP 470 -- Removing External Hosting Support on PyPI](https://www.python.org/dev/peps/pep-0470/) removed external downloads from PyPI. Fetching by default a download from outside PyPI violates this condition, because it silently performs a download external to PyPI (thus, it is also a security concern). So, `pip install graphviz` should not download GraphViz, unless the user explicitly requests so.

An optional external download could be done with a command line option to `setup.py`, as done in the package `dd`, described [here](https://github.com/johnyf/dd/tree/e5aa95bf118db18699d4f0c297e0f9dfc68243a7#dd-fetching-cudd), and implemented with [this script](https://github.com/johnyf/dd/blob/e5aa95bf118db18699d4f0c297e0f9dfc68243a7/download.py). However, such a download seems unnecessary and a mix of concerns, since no bindings to GraphViz need be compiled.

Perhaps a more dependable solution is to include GraphViz within a wheel for `graphviz`. This conforms to PEP 470, since no external download occurs. However, the main effect will be to unnecessarily increase the wheel's size, and most users will already have GraphViz installed from their OS's package manager.

Also, please remember to include the license of GraphViz if it is part of the distribution of the `graphviz` package.

**Comment by xoviat** [comment]
> GraphViz is distributed separately, and is available in package managers for the most widely used operating systems. As far as I can tell, it is used as an external program by the Python package graphviz, so no need to compile any bindings. Therefore no need to install it as part of the graphviz package.

I am well aware of the Python standards, considering that I'm a maintainer on a number of Python projects. Aside from the standards, this type of external dependency wastes developer time when a library is included as a dependency but does not provide all of the functionality required for the library to work. I remember back to the days of easy_install when you would set aside 30 minutes or more just to install extensions with a c library.

What I am suggesting is why pypandoc provides: a method that can be invoked at runtime to automatically download pypandoc if it is not installed. This is completely within the Python standards because it is not invoked on pip installation (though I do personally violate this rule on some of my packages).

**Comment by johnyf** [comment]
I misinterpreted the OP, by combining it with a comment [above](https://github.com/xflr6/graphviz/issues/39#issuecomment-300258217). Thanks for clarifying the intent. I agree that a convenience function to download `graphviz` at runtime does not interfere in any way with PyPI, package managers, or installation procedures. To ensure security, the download needs to happen only if explicitly requested (e.g., by calling the convenience function, or by passing an argument), not by default.

> (though I do personally violate this rule on some of my packages)

It would be worth considering alternative ways.

**Comment by xflr6** [comment]
Thanks for #40 and the discussion (and sorry for the long delay).

I am mildly sceptical: Scraping the Graphviz website seems easy to break (possibly requiring constant repair when something changes on their end). There are no tests yet and maybe truely verifying automatic installation on different plaforms is out of scope.

Under Windows, it seems kind of unnatural to open a command line and do something like `python -m graphviz user_install` to install Graphviz instead of using the installer. Under Linux, `apt install graphviz` seems more common. IIUC, the current version may fail on non-debian based distros (can we even assume that `~/bin` is on the user's PATH?).

Anouncing this functionality and then having it break in some or a lot of cases may not be a good idea for users and maintainers. However, one might still include it along with some big disclaimer. On the other hand, maybe it's better to improve documentation on installing the dependency.

So I am still +-1 on this. The code would probably need some refactoring though (e.g.: why scrape the download pages for all platforms if you know beforehand, which one you need?, why split at `"` when you can make the regex match the quoted content?, is it safe to assume that the first download on the linux page actually contains the latest version number for all platforms?).

**Comment by xoviat** [comment]
> I am mildly sceptical: Scraping the Graphviz website seems easy to break (possibly requiring constant repair when something changes on their end). There are no tests yet and maybe truely verifying automatic installation on different plaforms is out of scope.

The graphviz website has been the same for a decade. There's no reason to believe that it will suddenly change.

> Anouncing this functionality and then having it break in some or a lot of cases may not be a good idea for users and maintainers. However, one might still include it along with some big disclaimer. On the other hand, maybe it's better to improve documentation on installing the dependency.

Why does pip exist at all? Why not have people download the packages and then unzip them? Answer: command line tools save time. 

> The code would probably need some refactoring though (e.g.: why scrape the download pages for all platforms if you know beforehand, which one you need?, why split at " when you can make the regex match the quoted content?, is it safe to assume that the first download on the linux page actually contains the latest version number for all platforms?).

I cannot test this on other platforms at this time, but it's better to give people a starting place for other platforms than nothing. With respect to the regex, I agree. That change was simply a hacked-together patch to get it working.

**Comment by xoviat** [comment]
Wow. I'll eat my hat:

> Due to organizational changes, the Graphviz web site will see some modifications in the near future. In particular, it will probably no longer provide binary packages for Windows and Macs. The latter can be obtained via Macports or Home Brew. If someone wants to set up Appveyor for Windows, we would be grateful.

**Comment by xflr6** [comment]
Thats sad (there is [some hope](https://github.com/ellson/graphviz/issues/1219) for new Windows binaries though).

Closing this and #40 for now: maybe revisit in case new binaries are provided and the state of the web site looks more stable.
