### ISSUE TITLE
Use pipe on stdin/stdout

### ISSUE THREAD

**Issue by candlerb** [xflr6/graphviz#9]
'dot' accepts input on stdin and generates output on stdout when not given a filename:

~~~
$ dot -Tpng <ert.dot >ert.png
~~~

For use within an app framework it would be convenient if the graphviz library's "render" used subprocess.communicate to generate the graph, and returned a string. Then no temporary files would be required either for the graphviz source or for the generated image.

(People still might want the option for the output to be written directly to a file, e.g. if it's very large)

**Comment by xflr6** [comment]
Thanks for the suggestion. I imagine this would be most useful in a webapp for producing inline SVG to be presented to the client. Or maybe you have something different in mind?

I do not want to change the signature of the `render()`-method in a backwards-incompatible way (or complicate it deliberately). Also, due to the pre-buffering of `communicate` I do not see this as a very general method. So  a possible API for this would be something like a  `pipe()`-method that takes no arguments and returns the compiled `stdout` as `str` (`bytes` on PY3). Hm, what about `stderr` and compile failiures?

Maybe you would like to make a proposal in form of a pull request?
